### ISSUE TITLE
Deployment script mismatches gauges and reward distributors

### ISSUE THREAD

**Issue by zobront** [stake-dao/only-boost#59]
In Deployment.s.sol, a list of gauges (Curve) and reward distributors (StakeDAO) are provided to migrate. 

The gauge list is 162 elements long, but the reward distributor list is only 160 elements long, missing the corresponding reward distributors to the final two gauges.

The match between these two lists is crucial, as funds will be migrated and permissions granted accordingly.

### Recommendation

Beyond adding the two missing reward distributors, I recommend adding checks to the deployment script to ensure the two lists are equal length and the addresses at each index are intended to correspond with each other:
```diff
+ require(rewardDistributors.length == gauges.length);
  for (uint256 i = 0; i < rewardDistributors.length; i++) {
+     IStrategy oldStrategy = IStrategy(locker.governance());
+     require(oldStrategy.multigauges(gauges[i]) == rewardDistributors[i]); 
      ...
  }
```

**Comment by kobe-eth** [comment]
Added the checks, but note to self: 

Before the deployment, the array must be up to date after, and the factory should be killed
